# Generated by Django 4.1 on 2023-05-27 11:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('seanses', '0002_alter_schedule_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='barcode',
            field=models.ImageField(upload_to='barcode_images/', verbose_name='Баркод'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Уникальный UUID'),
        ),
    ]
