# Generated by Django 4.1 on 2023-05-16 14:54

import apps.movies.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('trailer', models.URLField(verbose_name='Трейлер')),
                ('poster', models.ImageField(upload_to=apps.movies.utils.upload_instance, verbose_name='Постер')),
            ],
            options={
                'verbose_name': ('Фильм',),
                'verbose_name_plural': 'Фильмы',
            },
        ),
        migrations.CreateModel(
            name='MovieGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='MovieDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premiere', models.DateField(blank=True, null=True, verbose_name='Премьера')),
                ('actors', models.CharField(max_length=512, verbose_name='Актеры')),
                ('genre', models.ManyToManyField(to='movies.moviegenre', verbose_name='Жанр')),
                ('movie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='movies.movie', verbose_name='Фильм')),
            ],
            options={
                'verbose_name': 'Детали фильма',
                'verbose_name_plural': 'Детали фильмов',
            },
        ),
    ]
