# Generated by Django 4.1 on 2023-05-18 13:47

import apps.movies.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to=apps.movies.utils.upload_instance, verbose_name='Постер'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='trailer',
            field=models.URLField(blank=True, null=True, verbose_name='Трейлер'),
        ),
    ]
